export const MODULES = [
  {
    key: 'bingo',
    name: 'Bingo Humano',
    emoji: '🎯',
    icon: '/img/bingoh.png',
    gradient: 'from-rose-400 to-pink-500',
    bg: 'bg-rose-500',
    description: '¡Encontrá al invitado y respondé las preguntas!',
    adminPath: '/admin/bingo',
    implemented: true,
  },
  {
    key: 'quiz',
    name: 'Quiz',
    emoji: '❓',
    icon: '/img/quiz.png',
    gradient: 'from-emerald-400 to-teal-500',
    bg: 'bg-emerald-500',
    description: 'Trivia en tiempo real con puntaje por velocidad. ¿Quién sabe más del grupo?',
    adminPath: '/admin/quiz',
    implemented: true,
  },
  {
    key: 'adivina',
    name: 'Adivina Quién',
    emoji: '💍',
    icon: '/img/adivina.png',
    gradient: 'from-violet-400 to-indigo-500',
    bg: 'bg-violet-500',
    description: '¿Quién maneja mejor? ¿Quién cocina más? Elegí entre los dos.',
    adminPath: '/admin/adivina',
    implemented: true,
  },
  {
    key: 'deseos',
    name: 'Deseos',
    emoji: '✨',
    gradient: 'from-amber-400 to-yellow-500',
    bg: 'bg-amber-500',
    description: 'Dejá un deseo especial para los novios.',
    adminPath: '/admin/deseos',
    implemented: true,
  },
  {
    key: 'timeline',
    name: 'Timeline',
    emoji: '📖',
    gradient: 'from-blue-400 to-sky-500',
    bg: 'bg-blue-500',
    description: 'La historia de los novios, momento a momento.',
    adminPath: '/admin/timeline',
    implemented: true,
  },
  {
    key: 'lightning',
    name: 'Lightning Round',
    emoji: '⚡',
    gradient: 'from-yellow-400 to-orange-400',
    bg: 'bg-yellow-500',
    description: 'Ronda relámpago para desempates. Próximamente.',
    adminPath: '/admin/lightning',
    implemented: false,
  },
  {
    key: 'playlist',
    name: 'Pedidos de Temas',
    emoji: '🎵',
    gradient: 'from-purple-400 to-fuchsia-500',
    bg: 'bg-purple-500',
    description: 'Los invitados piden sus canciones favoritas. Próximamente.',
    adminPath: '/admin/playlist',
    implemented: false,
  },
]

export function getModule(key) {
  return MODULES.find(m => m.key === key)
}
